apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  type: ClusterIP
  selector:
    role: api
