apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
  selector:
    role: frontend
